- project:
    check:
      jobs:
        - "thoth-pytest"
    gate:
      queue: "thoth-station/core"
      jobs:
        - "thoth-pytest"

    kebechet-auto-gate:
      queue: "thoth-station/core"
      jobs:
        - "thoth-pytest"
